# Generated by Django 3.2.9 on 2021-11-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=200)),
            ],
        ),
    ]
